@startuml
!theme plain

Object Project {
code
name
description
start date
end date
sprint duration
number of planned sprints
project status
budget
' Report could be its own conceptual class, but we are not modelling with detail yet
'Report
}

Object ProductBacklog


Object Sprint {
sprint number
start date
end date
}


Object "SprintBacklog" as SB {
US effort estimate
}

Object "UserStory" as US {
us number
actor
description
acceptance criteria
status
priority
}

Object Ceremony {
type
date
description
}


Project "                          1" -down- "*" Sprint: entails >
Sprint "                     1" -down- "           1" SB: defines >
US "                                                                     *" -right- "          1" SB: picked into >
Project "1" -left- "1" ProductBacklog: includes >
ProductBacklog "1" -down- "*" US: collected in <
Sprint "1" -right- "*" Ceremony: includes >

@enduml