@startuml


class EstimateEffortController {
projectList: ProjectList
estimateEffortUserStory (int projectCode, \nint sprintNumber, String idUserStory, double effort)
}

class ProjectList {
projectList: List<Project>
getProject(projectCode)
}

class Project {
code: int
name: String
description: String
startDate: Date
endDate: Date
customer: String
sprintDuration: int
numberOfPlannedSprints: int
projectStatus: String
budget: double
resourceList: ResourceList
sprintList: SprintList
getProductBacklog()
getSprintList()
}

class ProductBacklog {
userStories: List<UserStory>
completedUserStories : List<UserStory>
factoryUserStory : IFactoryUserStory
getUserStory(UserStoryID)
}

class SprintList {
sprintList: List<Sprint>
getSprint(sprintNumber)
}

class Sprint {
sprintNumber: int
startDate: Date
endDate: Date
sprintBackLog: List<US>
existsUserStory (userStory)
validEffortEstimate(effort)
estimateEffortForUserStory (userStoryID, effort)
}

class UserStory {
id : String
actor : String
text : String
acceptanceCriteria : String
status : String
getID()
}

EstimateEffortController "      1" o-- "      1" ProjectList
ProjectList "       1" *-- "                     *" Project
Project "                             1 " o-- "1  " ProductBacklog
ProductBacklog "1  " *-- "                                              * " UserStory
Project "1" o-- "                       1" SprintList
SprintList "              1" *-- "                                *" Sprint
Sprint "                                            1 "*-- " *  " UserStory

@enduml