@startuml
"Team Member" -> System: Estimate the effort of a user story in a sprint \n (projectCode, sprintNumber, userStoryID, effort)
"Team Member" <-- System: Effort of a user story estimated
@enduml