@startuml
left to right direction

:Profile: as Profile
Profile <|-- :Administrator:
Profile <|-- :User:
Profile <|-- :Manager:
:User:<|-- :Team Member:
:User:<|-- :Product Owner:
:User:<|-- :Project Manager:
:User:<|-- :Scrum Master:

rectangle "Project Management System"{

User -- (Search project)
User -- (List projects I'm allocated to)

:Administrator: as Administrator
Administrator -- (Create profile)
Administrator -- (Register users)
Administrator -- (List all accounts)
Administrator -- (Search for users)
Administrator -- (Change user profile)
Administrator -- (Inactivate user account)
Administrator -- (Activate user account)
Administrator -- (Create Project Typology)
Administrator -- (Add Business Sector)
Administrator -- (Add A Customer)

:Manager: as Manager
Manager -- (Create projects)
Manager -- (Manage resources)
Manager -- (Search all projects)
Manager -- (Access to all projects)
Manager -- (Edit Project)
Manager -- (View All allocation reports)
Manager -- (Register/Create New Project)
Manager -- (Associate user as Team Member of project)
Manager -- (Define PO of a project)
Manager -- (Define the Scrum Master)
Manager -- (List of all human resources in a project )
Manager -- (List of all projects)

:Team Member: as "Team Member"
"Team Member" -- (Create Sprint Backlog)
"Team Member" -- (Add user story to the Sprint Backlog)
"Team Member" -- (Create tasks)
"Team Member" -- (Edit tasks)
"Team Member" -- (Update tasks)
"Team Member" -- (Register work tasks done)
"Team Member" -- (View the status of activities in the project)
"Team Member" -- (View own allocation reports)

:Project Manager: as "Project Manager"
"Project Manager" -- (List the information of all projects that manages)
"Project Manager" -- (Edit Project)
"Project Manager" -- (View KPI report)
"Project Manager" -- (Export KPI report)

:Product Owner: as "Product Owner"
"Product Owner" -- (List the information of all projects that manages)
"Product Owner" -- (Create user stories)
"Product Owner" -- (Add user stories to the project backlog)
"Product Owner" -- (Edit user stories)
"Product Owner" -- (Remove user stories)
"Product Owner" -- (View KPI report)

:Scrum Master: as "Scrum Master"
"Scrum Master" -- (List the information of all projects that manages)
"Scrum Master" -- (Scrum ceremonies)
}
@enduml