@startuml
title List all Project in the web UI
salt
{+
.
{
.{+
"<b>Project 1                    "|[<&magnifying-glass>]
"<b>Project 2                    "|[<&magnifying-glass>]
"<b>Project 3                    "|[<&magnifying-glass>]
"<b>Project 4                    "|[<&magnifying-glass>]
"<b>Project 5                    "|[<&magnifying-glass>]
"<b>Project 6                    "|[<&magnifying-glass>]
"<b>Project 7                    "|[<&magnifying-glass>]
"<b>Project 8                    "|[<&magnifying-glass>]
"<b>Project 9                    "|[<&magnifying-glass>]
"<b>Project 10                   "|[<&magnifying-glass>]
}
.{[Create Sprint]}

}
}
@enduml
