@startuml
!theme plain
hide footbox
autonumber
title "US019 - As Project Manager, I want to create a sprint."

actor ProjectManager as User
participant ": CreateSprintUI" as UI
participant "sprintDTO : SprintDTO" as DTO
participant ": CreateSprintController" as Controller
participant ": SprintService" as Services
participant "projectCodeVO : ProjectCode" as ProjecCode
participant ": ProjectRepository" as Repository
participant "sprintNumberVO : SprintNumber" as SprintNumber
participant "sprintID : SprintID" as SprintID
participant "timePeriod : TimePeriod" as TimePeriod
participant "factorySprint :FactorySprintImpl" as Factory
participant "sprint : Sprint" as Sprint
participant "sprint : Sprint" as Sprint
participant ": SprintRepository" as SprintRepository
participant "sprintData : HashMap" as HashMap


activate User #FFBBBB
User ->  UI: Requests creation of a sprint \n(projectCode, sprintNumber, startDate, endDate)

activate UI #FFBBBB
UI --> DTO **: create(projectCode, \n sprintNumber,\n startDate, endDate)
UI -> Controller: createSprint(sprintDTO)

activate Controller #FFBBBB
Controller -> Services: createSprint(sprintDTO)

activate Services #FFBBBB
Services --> ProjecCode ** : create(sprintDTO.projectCode)
Services -> Repository: containsID(projectCodeVO)

activate Repository #FFBBBB
Repository -->Services: true
deactivate

Services --> SprintNumber ** : create(sprintDTO.sprintNumber)
Services --> SprintID ** : create(projectCodeVO, sprintNumberVO)
Services --> TimePeriod ** : create (newSprintDTO.startDate, sprintDTO.endDate)
Services -> Factory: createSprint(sprintID, timePeriod)

activate Factory #FFBBBB
Factory --> Sprint ** : create (sprintID, \n timePeriod)
Factory --> Services : sprint
deactivate

Services -> SprintRepository :save(sprint)

activate SprintRepository #FFBBBB
SprintRepository -> HashMap : contains(sprintID)

activate HashMap #FFBBBB
HashMap --> SprintRepository : false
SprintRepository -> HashMap : put(sprintID, sprint)
HashMap --> SprintRepository: null
deactivate HashMap #FFBBBB

SprintRepository --> Services: true
deactivate

Services --> Controller: true
deactivate

Controller --> UI: true
deactivate

UI --> User: Confirms created Sprint
deactivate UI
deactivate User #FFBBBB
@enduml