@startuml
!theme plain
hide footbox

actor ProjectManager as User
participant ": CreateSprintUI" as UI
participant "sprintDTO : SprintDTO" as DTO
participant ": CreateSprintController" as Controller
participant ": ProjectList" as ProjectList
participant "project : Project" as Project
participant ":SprintList" as SprintList
participant "sprint : Sprint" as Sprint

activate User #FFBBBB
User ->  UI: Requests creation of a sprint (projectCode, sprintNumber, startDate, endDate)

activate UI #FFBBBB
UI --> DTO **: create(sprintNumber, startDate, endDate)
UI -> Controller: createSprint(projectCode, sprintDTO)
activate Controller #FFBBBB

Controller -> ProjectList: getProject(projectCode);
activate ProjectList #FFBBBB
ProjectList --> Controller: project
deactivate ProjectList
Controller -> Project: createSprint(sprintDTO);
activate Project #FFBBBB

Project -> SprintList: addSprint(sprintDTO);
activate SprintList #FFBBBB

SprintList -> Sprint **: create(sprintDTO);
SprintList -> SprintList: hasSprint(sprint);
SprintList -> SprintList: add(sprint);

SprintList --> Project: true
deactivate SprintList

Project --> Controller: true
deactivate Project

Controller --> UI : true
deactivate Controller

UI --> User: Confirms created Sprint
deactivate UI
deactivate User #FFBBBB
@enduml