@startuml

"Project Manager" -> System: Requests creation of a sprint
'"Project Manager" <-- System: Authorization granted
'"Project Manager"  -> System: Add user stories to be part of the sprint
"Project Manager"  <-- System: Sprint created with success
@enduml