@startuml

"Project Manager" -> System: Requests creation of a sprint\n(projectCode, sprintNumber, startDate, endDate)
'"Project Manager" <-- System: Authorization granted
'"Project Manager"  -> System: Add user stories to be part of the sprint
"Project Manager"  <-- System: Confirms created Sprint
@enduml