@startuml
!theme plain
autonumber
hide footbox
title "US008 - As Administrator, I want to add a business sector"

participant Client
participant Springboot
participant "businessSectorDTO : BusinessSectorDTO" as businessSectorDTO
participant ":BusinessSectorController" as Controller
participant ":BusinessSectorService" as Service
participant "businessSectorFactory :IBusinessSectorFactory" as Factory
participant "businessSectorRepository :BusinessSectorRepository" as Repository
participant ":AssemblerData" as Assembler
participant "businessSectorJPA :IBusinessSectorRepositoryJPA" as RepositoryJPA
participant ":BusinessSectorMapper" as Mapper
participant "response : ResponseEntity<businessSectorOutputDTO>" as response

Client -> Springboot : POST /businessSector \n{"businessSectorDesignation": "businessSectorDesignation"}
activate Client #FFBBBB

activate Springboot #FFBBBB
Springboot --> businessSectorDTO ** : create(businessSectorDesignation)
Springboot -> Controller : createBusinessSector\n(businessSectorDTO)
deactivate Springboot

activate Controller #FFBBBB
Controller -> Service :createBusinessSector(businessSectorDTO)

activate Service #FFBBBB

Service -> Factory :createBusinessSector(businessSectorID, businessSectorDesignation)
activate Factory #FFBBBB
Factory --> "businessSector :BusinessSector" ** :create(businessSectorID, businessSectorDesignation)
Factory --> Service :businessSector
deactivate Factory

Service -> Repository :save(businessSector)
activate Repository #FFBBBB


Repository -> RepositoryJPA :existsByBusinessSectorDesignation(businessSectorDesignation)
activate RepositoryJPA #FFBBBB
RepositoryJPA --> Repository :businessSectorDesignation
deactivate RepositoryJPA
Repository ->Repository :existBusinessSector(businessSector)


Repository -> Assembler :toDate(businessSector)
activate Assembler #FFBBBB
Assembler --> "businessSectorJPA :BusinessSectorJPA" ** :Create(businessSector)
Assembler --> Repository: businessSectorJPA
deactivate Assembler

Repository -> RepositoryJPA : save(businessSectorJPA)
activate RepositoryJPA #FFBBBB
RepositoryJPA --> Repository : savedBusinessSectorJPA
deactivate RepositoryJPA
Repository -> Assembler : toDomain(savedBusinessSectorJPA)
activate Assembler #FFBBBB
Assembler --> "businessSector :BusinessSector" ** :Create(businessSectorJPA)
Assembler --> Repository : savedBusinessSector
deactivate Assembler
Repository -->Service: savedBusinessSector

deactivate Repository
Service --> Controller : businessSectorDTO
deactivate Service

Controller -> Mapper :toOutputDTO(businessSectorDTO)
activate Mapper #FFBBBB
Mapper -->"businessSectorOutputDTO:BusinessSectorDTO" ** :Create(businessSectorDTO)
Mapper --> Controller :businessSectorOutputDTO
deactivate Mapper
Controller --> response ** : create(businessSectorOutputDTO, HttpStatus.CREATED)
Controller --> Client : Confirms businessSector creation
deactivate Controller

@enduml