@startsalt
{

title Create Project
Code
{+
   .
   "                         "
}
.
Name
{+
   .
   "                         "
}
.
Description
{+
   .
   "                         "
}
.
Customer
{+
   .
   "                         "
}
.
{ ^Start date <&calendar>^}

.
{ ^End date <&calendar>^}
.
Project Status
^           ^
.
Typology
^           ^
.
Sprint Duration
^           ^
.
Number of Planned Sprints
{+
   .
   "                         "
}
.
Budget
{+
   .
   "                         "
}

{  [<&circle-check>Save ] |
[<&circle-x>Cancel]}


}




@endsalt