@startsalt
{

title Create Project
Code
{+
   .
   "                         "
}
Name
{+
   .
   "                         "
}
Description
{+
   .
   "                         "
}
Start Date
{+
   .
   "                         "
}
End Date
{+
   .
   "                         "
}
Customer
{+
   .
   "                         "
}
Sprint Duration
{+
   .
   "                         "
}
Number of Planned Sprints
{+
   .
   "                         "
}
Project Status
{+
   .
   "                         "
}
Budget
{+
   .
   "                         "
}

{  [<&circle-check>Save ] |
[<&circle-x>Cancel]}


}




@endsalt