@startuml

class ViewScrumBoardController {
projectList: ProjectList
sprintList: SprintList
viewScrumBoard(projectCode, sprintNumber)
}

class ProjectList {
projectList: List<Project>
getProject(projectCode)
}

class Project {
code: int
name: String
description: String
startDate: Date
endDate: Date
customer: String
sprintDuration: int
numberOfPlannedSprints: int
projectStatus: String
budget: double
resourceList: ResourceList
sprintList: SprintList
getSprintList();
}

class SprintList {
sprintList: List<Sprint>
getSprint(sprintNumber)
}

class userStoryDTO{
id: String
status: Status
}

class Sprint{
sprintNumber: int
startDate: Date
endDate: Date
sprintBackLog: List<US>
viewScrumBoardList();
}

class UserStory {
id : String
actor : String
text : String
acceptanceCriteria : String
status : Status
}

class UserStoryAssembler{
toDTO(userStory)
}

ViewScrumBoardController "1" o-- "1" ProjectList
ProjectList "1" *-- "*" Project
Project "1" o-- "1" SprintList
SprintList "1" *-- "*" Sprint
Sprint "1 " *-- " *  " UserStory
ViewScrumBoardController ..> Project
Sprint .right.> userStoryDTO
ViewScrumBoardController ..> SprintList
Sprint "1" o-right- "1" UserStoryAssembler
UserStoryAssembler ..> userStoryDTO
ViewScrumBoardController .down.> Sprint


@enduml