@startuml
!theme plain
hide footbox

actor TeamMember as User
participant ": ViewScrumBoardUI" as UI
participant ": ViewScrumBoardController" as Controller
participant ": ProjectList" as List
participant "project : Project" as Project
participant ": SprintList" as SprintList
participant "sprint : Sprint" as Sprint
participant "lsUS : List<UserStory>" as DTOList
participant ": UserStoryAssembler" as Assembler
participant "userStoryDTO : UserStoryDto" as Dto
participant "userStory : UserStory" as US

activate User #FFBBBB
User -> UI: request Scrum Board of the current sprint(projectCode, sprintNumber)

activate UI #FFBBBB
UI -> Controller: viewScrumBoard(projectCode, sprintNumber);
activate Controller #FFBBBB

Controller -> List: getProject(projectCode);
activate List #FFBBBB
List --> Controller: project
deactivate List

Controller -> Project: getSprintList();
activate Project #FFBBBB
Project --> Controller: sprintList
deactivate Project

Controller -> SprintList: getSprint(sprintNumber);
activate SprintList #FFBBBB
SprintList --> Controller: sprint
deactivate SprintList

Controller -> Sprint: viewScrumBoard();
activate Sprint #FFBBBB

Sprint -> DTOList **: create

loop for each UserStory in SprintBacklog


Sprint -> Assembler: toDTO (userStory);
activate Assembler #FFBBBB
Assembler --> Dto **: toDTO;
deactivate Assembler
Sprint -> DTOList: add(userStoryDTO);
activate DTOList #FFBBBB
deactivate DTOList
end

Sprint --> Controller: lsUS
Controller --> UI: lsUS
deactivate Controller

UI --> User: Scrum Board presented
deactivate User
@enduml