@startuml
!theme plain
hide footbox

actor Administrator  as Administrator
participant ": AddCustomerUI" as UI
participant ": AddCustomerController" as Controller
participant ": CustomerList" as List
'participant " defaultProfile : Profile"
'participant ": AccountList" as AccountList
participant "customerDTO : CustomerDTO" as DTO
participant " newCustomer : Customer" as newCustomer


activate Administrator #FFBBBB
Administrator ->  UI : Add Customer (name)

activate UI #FFBBBB
UI -> Controller : addCustomer(addCustomerDTO)

activate Controller #FFBBBB
'Controller -> List : defaultCustomer = getCustomerByName("name")

'activate ProfileList #FFBBBB
'deactivate ProfileList

Controller -> List : addCustomer(addCustomerDTO)

activate List #FFBBBB
List -> DTO : name = getName()

activate DTO #FFBBBB
deactivate DTO

List -> List : isNameInUse(name)

List --> newCustomer ** : newCustomer = create(customerDTO)
List -> List : save(newCustomer)

List --> Controller : Confirms new customer registration
deactivate List

Controller --> UI : Confirms new customer registration
deactivate Controller
UI --> Administrator : Confirms new customer registration
deactivate UI
@enduml