@startuml
!theme plain
skinparam linetype ortho
package "Account" as Acc #Wheat{
    Object Account <<Entity>> <<Root>> {
    }
}
Object name <<VO>> #powderblue
Object phoneNumber <<VO>> #powderblue
Object email <<VO>> #powderblue
Object photo <<VO>> #powderblue
Object accountStatus <<VO>> #powderblue

Account -->  name
Account -->  phoneNumber
Account -->  email
Account -->  photo
Account -->  accountStatus

package "Resource" as Res #Wheat {
    Object Resource <<Entity>> <<Root>> {
    }
}

Object timePeriod <<VO>> #powderblue
Object percentageOfAllocation <<VO>> #powderblue
Object costPerHour <<VO>> #powderblue
Object role <<VO>> #powderblue

Resource --> timePeriod
Resource --> percentageOfAllocation
Resource --> costPerHour
Resource --> role


package "Project" as Proj #Wheat {
    Object Project <<Entity>> <<Root>> {
    }
}

Object projectCode <<vo>> #powderblue
Object projectName <<vo>> #powderblue
Object durationInWeeks <<vo>> #powderblue
Object numberOfPlannedSprints <<vo>> #powderblue
Object projectStatus <<vo>> #powderblue
Object projectBudget <<vo>> #powderblue

package Typology as Typo #Wheat {
    Object Typology <<Entity>> {
    designation
    }
    }

package BusinessSector as Bus #Wheat {
Object BusinessSector <<Entity>> {
            designation
            }
            }

package Customer as Cost #Wheat {
    Object Customer <<Entity>> {
    designation
    }
    }

package "Sprint" as Spr #Wheat {
    Object Sprint <<Entity>> <<Root>> {
    sprint number
    start date
    end date
    US effort estimate
    }
    Object UserStoryInSprint <<Entity>> {
    }
}
package "UserStory" as US #Wheat{
    Object UserStory <<Entity>> <<Root>>
}

Object uSNumber <<VO>> #powderblue
Object actor <<VO>> #powderblue
Object description <<VO>> #powderblue
Object acceptanceCriteria <<VO>> #powderblue
Object status <<VO>> #powderblue
Object priority <<VO>> #powderblue

UserStory --> uSNumber
UserStory --> actor
UserStory --> description
UserStory --> acceptanceCriteria
UserStory --> status
UserStory --> priority

Project --> projectCode
Project --> projectName
Project --> description
Project --> timePeriod
Project --> durationInWeeks
Project --> numberOfPlannedSprints
Project --> projectStatus
Project --> projectBudget

package "Profile" as Prof #Wheat {
Object Profile <<Entity>> <<Root>> {
profileName
}


BusinessSector --> "1" Project
Customer --> "1" Project
Typology --> "1" Project
Sprint "1" -- "*" UserStoryInSprint
Account -up-> "             1" Profile
'Resource "1" -down- "1" Role
Project "1" - "*" Sprint
Project "1" -> "*" UserStory
Project -left-> "*" Resource
UserStoryInSprint "*" - "1" UserStory
Resource "1" <- "*" Account
@enduml
