 @startuml
!theme plain

Object Account {
name
phone number
email
photo: [0..1]
account status: [Active, Inactive]
}

Object Profile {
name
}

Object Resource {
start date
end date
percentage of allocation
cost per hour
}

Account "        1"-right- "    1" Profile : has >
Account "1"-- "1" Profile : controlled by Admin <
Account "1   " --- "*" Project : controlled \n by Manager <
Account "1" -right- " 1  " Resource : has <
Resource "1..*" -left- "1" Project : involves <

Object Typology {
designation
}

Account "1" -down-"*" Typology : created by Admin <
Typology "1" -- "                                   *" Project : has <

Object BusinessSector {
designation
}

Account "1" -down- "*" BusinessSector : created by Admin <
BusinessSector "1" -- "*" Project : has <

Object Customer {
designation
}

Account "1" -down- "*" Customer : created by Admin <
Customer "1" -- "*" Project : has <

Object Project {
code
name
description
start date
end date
sprint duration
number of planned sprints
project status
budget
}

Object Role {
role name
}

Object ProductBacklog

Object UserStory {
us number
actor
description
acceptance criteria
status
priority
}

Object Sprint {
sprint number
start date
end date
US effort estimate
}

Object Ceremony {
type
date
description
}

Object SprintBacklog {
}

Object ScrumBoard

Object Task {
name
description
start date
end date
effort estimate
task type
hours spent
percentage of execution
}

Profile "1" -down- "  2..*" Profile: created by Admin >
Project "1" -down- "*" Sprint: entails >
Project "1" -left- "1" ProductBacklog: includes >
ProductBacklog "1" -down- "*" UserStory: collected in <
Sprint "1" -down- "1" SprintBacklog: defines >
Sprint "1" -right- "*" Ceremony: includes >
UserStory "*" -- "1" SprintBacklog: picked into >

Resource "1" -right- "1" Role : plays >
SprintBacklog "1" -down- "   1..*" Task: contains >
SprintBacklog "1" -left- "1" ScrumBoard: status shown in >
Resource "1" -down- "*" Task: works on >
ScrumBoard "1" -down- "*" Task: status shown in <

note "The creation of tasks is done by the team members.\nThe users available for the activities are the team members, the PO and the SM." as N1
Task .down. N1

@enduml
