@startuml
!theme plain
'skinparam linetype ortho

skinparam package {
    backgroundColor SandyBrown
}

skinparam object {
    backgroundColor LightCyan
}

skinparam object<<ID>> {
    backgroundColor LightSkyBlue
}

skinparam object<<Entity>> {
    backgroundColor Moccasin
}

' - Value Objects
' -- plain VOs
Object Name <<VO>>
Object PhoneNumber <<VO>>
Object Photo <<VO>>
Object AccountStatus <<VO>>
Object TimePeriod <<VO>>
Object PercentageOfAllocation <<VO>>
Object CostPerHour <<VO>>
Object Role <<VO>>
Object UserStoryActor <<VO>>
Object Description <<VO>>
Object UserStoryAcceptanceCriteria <<VO>>
Object ProjectName <<VO>>
Object SprintDuration <<VO>>
Object NumberOfPlannedSprints <<VO>>
Object ProjectStatus <<VO>>
Object ProjectBudget <<VO>>
Object SprintNumber <<VO>>
Object UserStoryEffortEstimate <<VO>>
Object UserStoryStatus <<VO>>
Object UserStoryPriority <<VO>>
Object UserStoryNumber <<VO>>
Object Designation <<VO>>

' -- DomainID VOs
Object ProjectCode <<VO>> <<ID>>
Object UserStoryID <<VO>> <<ID>>
Object UserStoryInSprintID <<VO>> <<ID>>
Object SprintID <<VO>> <<ID>>
Object Email <<VO>> <<ID>>
Object ProfileName <<VO>> <<ID>>
Object TypologyID <<VO>> <<ID>>
Object BusinessSectorID <<VO>> <<ID>>
Object CustomerID <<VO>> <<ID>>

' - Entities in Aggregates (packages)
package "Project" as Proj {
    Object Project <<Entity>> <<Root>>
    Object ProductBacklog <<Entity>>
}

Project -down-> "1" ProductBacklog
ProductBacklog --> "*" UserStoryID
Project --> "1" ProjectCode
Project -up-> "1" ProjectName
Project --> "1" Description
Project --> "1" TimePeriod
Project --> "1" SprintDuration
Project --> "1" NumberOfPlannedSprints
Project --> "1" ProjectStatus
Project -up-> "1" ProjectBudget

package "Sprint" as Spr {
    Object Sprint <<Entity>> <<Root>>
    Object UserStoryInSprint <<Entity>>
}

SprintID --> "1" ProjectCode
SprintID --> "1" SprintNumber
Sprint --> "*" UserStoryInSprint
Sprint --> "1" ProjectCode
Sprint --> "1" SprintID
Sprint --> "1" TimePeriod

UserStoryInSprint --> "1" UserStoryID
UserStoryInSprint --> "1" UserStoryEffortEstimate
UserStoryInSprint --> "1" UserStoryInSprintID
UserStoryInSprintID --> "1" UserStoryID
UserStoryInSprintID --> "1" SprintID

package "UserStory" as US {
    Object UserStory <<Entity>> <<Root>>
}

UserStoryID --> "1" ProjectCode
UserStoryID --> "1" UserStoryNumber
UserStory --> "1" UserStoryID
UserStory --> "1" UserStoryActor
UserStory --> "1" Description
UserStory --> "1" UserStoryAcceptanceCriteria
UserStory --> "1" UserStoryStatus
UserStory --> "1" UserStoryPriority


package "Account" as Acc {
    Object Account <<Entity>> <<Root>>
}

Account --> "1" Name
Account -->  "1" PhoneNumber
Account --> "1" Email
Account --> "1" Photo
Account --> "1" AccountStatus


package "Resource" as Res {
    Object Resource <<Entity>> <<Root>>
}

Resource -up-> "1" TimePeriod
Resource --> "1" PercentageOfAllocation
Resource --> "1" CostPerHour
Resource --> "1" Role
Resource --> "1" ProjectCode
Resource --> "1" Email

package Typology as Typo {
    Object Typology <<Entity>>
    }

Typology -up-> "1" Designation
Typology --> "1" TypologyID
Project -up-> "1" TypologyID

package BusinessSector as Bus {
    Object BusinessSector <<Entity>>
            }

BusinessSector -up-> "1" Designation
BusinessSector --> "1" BusinessSectorID
Project -up-> "1" BusinessSectorID

package Customer as Cost {
    Object Customer <<Entity>>
    }

Customer -up-> "1" Designation
Customer --> "1" CustomerID
Project -up-> "1" CustomerID

package "Profile" as Prof {
    Object Profile <<Entity>> <<Root>>
    }

Profile -up-> "1" ProfileName

Account -up-> "1" ProfileName

@enduml
