@startuml
skinparam style strictuml
left to right direction
skinparam groupInheritance 3

 class "Profile Account" as Profile {
   Type Profile
   Name
   E-mail
   Phone number
   Photo: [0..1]
   'the [0..1] in Photo indicates an optional value, see Craig 2004, p.121
   Status
 }

  class "Project User" {
  Role
  Code Project
  Start Date
  End Date
  }

 class Project{
 Code
 Name
 Description
 Start Date
 Sprint duration
 Number of planned sprints
 End Date
 Customer
 Business Sector
 Typology
 Project Status
 Budget
 Report
}

Profile <|-- Manager
Profile <|-- User
Profile <|-- Administrator

Administrator "1" -- "2..*" Profile: registers, associates, lists, activates, inactivates >
Manager "1"--- "1..*" Project: creates >
User "1" -- "1..*" "Project User": belongs >
"Project User" "1..*" -- "1" Project : participates >
Project "1" -- "1..*" "Team member": included <
Project "1" -- "1" "Scrum master": included <
Project "1" -- "1" "Product owner": included <
Project "1" -- "1  " "Project manager": included <
Project "1" -- "1" "Project backlog": comprises <
Project "1" -- "1..*" "Sprint backlog": comprises <
"Project manager" "1" -- "1..*" Project: edits >
@enduml