@startuml

actor Administrator as Administrator #white
participant "List User UI" as UI #white
participant "List Controller" as Controller #white
participant "Profile Account" as Account #white


Administrator ->  UI: Request list of all users (profile account) and their status
activate Administrator #FFBBBB
activate UI #FFBBBB
UI -> Controller: listUserAccounts()

activate Controller #FFBBBB
Controller -> Account: listUserAccounts()

'Controller --> UI: User account (profile account) and status listed

UI --> Administrator: Retrieve list
deactivate Administrator #FFBBBB
@enduml