@startuml
!theme plain
hide footbox
autonumber

skinparam sequence{
LifeLineBackgroundColor #FFBBBB
}

title US017 - As Product Owner, I want to create a user story and add it to the Product Backlog\n(creation of user story)

participant ": IUserStoryFactory" as factory
participant "infoDTO : NewUserStoryInfoDTO" as dto

-> factory : createUserStory(infoDTO)
activate factory

factory -> dto : .userStoryNumber
activate dto
dto --> factory : userStoryNumber
deactivate

factory -> dto : .projectCode
activate dto
dto --> factory : projectCode
deactivate

factory --> "userStoryID : UserStoryID" ** : create(userStoryNumber, projectCode)

factory -> dto : .actor
activate dto
dto --> factory: actor
deactivate

factory -> dto : .description
activate dto
dto --> factory: description
deactivate

factory -> dto : .acceptanceCriteria
activate dto
dto --> factory: acceptanceCriteria
deactivate


factory --> userStory ** :create (userStoryID,\n actor,\n description, \n acceptanceCriteria)

[<-- factory: userStory
@enduml