@startuml
!theme plain
hide footbox
autonumber

skinparam sequence{
LifeLineBackgroundColor #FFBBBB
}

title US017 - As Product Owner, I want to create a user story and add it to the Product Backlog\n(request handling at controller)

participant Client
participant SpringBoot
participant "infoDTO : NewUserStoryInfoDTO" as infoDTO
participant ": UserStoryController" as controller
participant " : UserStoryService" as service
participant "response : ResponseEntity<>" as response

Client -> SpringBoot : POST /projects/${projectCode}/productbacklog\n{"projectCode": "code",\n"userStoryNumber": "usNumber",\n"userStoryActor":"actor", "description":"description",\n"userStoryAcceptanceCriteria":"criteria",\n"userStoryPriority":"priority"}
activate Client

activate SpringBoot
SpringBoot --> infoDTO ** : create(projectCode, userStoryNumber,\n         userStoryActor, description,\n         userStoryAcceptanceCriteria,\n         userStoryPriority)
SpringBoot -> controller : createUserStory(infoDTO)
deactivate

controller -> service : createUserStory(infoDTO)
deactivate

activate service
ref over service : US017_CreateUserStorySD2

service --> controller : savedUserStory
deactivate

controller --> response ** : create(savedUserStory, HttpStatus.CREATED)
controller --> Client : response
@enduml