@startuml
skinparam linetype ortho

class CreateUserStoryController {
createUserStory(projectCode, userStoryDTO, priority)
}

class UserStoryService {
create (projectCode, userStoryDTO, priority)
}

class ProjectRepository {
containsID(projectCode)
}

interface IFactoryUserStory {
createUserStory(userStoryDTO, priority)
}

class FactoryUserStoryImpl {
createUserStory(userStoryDTO, priority)
}

class UserStoryID {
id: String
}

class UserStoryActor {
id: String
}

class UserStoryStatus {
enum: Status
}

class UserStoryAcceptanceCriteria {
acceptanceCriteria: String
}

class Description {
description: String
}

class UserStory {
}

class UserStoryRepository {
save(userStory)
containsID()
put(userStoryID, userStory)
}

class Project {
addToSet(userStoryID, priority)
}
/'
class ProjectCode {
projectCode :String
}
'/
class UserStoryDTO {
id : String
actor : String
text : String
acceptanceCriteria : String
}

CreateUserStoryController "1" o--"1" UserStoryService
UserStoryService "1" o--"1" ProjectRepository
CreateUserStoryController ..> UserStoryDTO
ProjectRepository "      1" *-- "                    *" Project
UserStoryDTO ..> UserStory


FactoryUserStoryImpl -..|> IFactoryUserStory
UserStoryID -..> FactoryUserStoryImpl
UserStoryActor-..> FactoryUserStoryImpl
UserStoryStatus-..> FactoryUserStoryImpl
UserStoryAcceptanceCriteria-..> FactoryUserStoryImpl
Description-..> FactoryUserStoryImpl
UserStory-..> FactoryUserStoryImpl
FactoryUserStoryImpl -..> UserStoryDTO
UserStoryService ..> IFactoryUserStory
UserStoryService ..> UserStoryRepository
UserStoryService ..> Project

@enduml