@startuml
!theme plain
hide footbox
autonumber

skinparam sequence{
LifeLineBackgroundColor #FFBBBB
}

title US017 - As Product Owner, I want to create a user story and add it to the Product Backlog\n(saving of user story)

participant ": IUserStoryRepository" as usRepository
participant "userStory : UserStory" as newUserStory
participant ": UserStoryJpaRepository" as jpa
participant ": UserStoryDomainDataAssembler" as assembler
participant ": UserStoryJpa" as userStoryJpa
participant "savedUserStory : UserStory" as savedUserStory

-> usRepository : save(userStory)

activate usRepository
usRepository -> newUserStory : identity()

activate newUserStory
newUserStory --> usRepository: userStoryID
deactivate

usRepository -> usRepository : containsID(userStoryID)
activate usRepository #DarkSalmon

usRepository -> jpa :existsById(userStoryID)

activate jpa
jpa --> usRepository : false
deactivate
deactivate

usRepository -> assembler : toData(userStory)

activate assembler
assembler --> userStoryJpa ** : create
assembler --> usRepository : userStoryJpa
deactivate

usRepository -> jpa : save(userStoryJpa)

activate jpa
'jpa --> savedUserStoryJpa ** : create
jpa --> usRepository : savedUserStoryJpa
deactivate

usRepository -> assembler : toDomain(savedUserStoryJpa)
activate assembler
assembler --> savedUserStory ** : create
assembler --> usRepository : savedUserStory
deactivate

[<-- usRepository : savedUserStory

@enduml