@startuml
!theme plain
hide footbox
title "US017 - As Product Owner, I want to create a user story and add it to the Product Backlog"

actor "Product Owner" as user
participant ": CreateUserStoryUI" as UI
participant "userStoryDTO : UserStoryDTO" as dto
participant ": CreateUserStoryController" as Controller
participant ": ProjectList" as ProjectList
participant "project : Project" as Project
participant "productBacklog : ProductBacklog" as ProductBacklog
participant ": UserStoryMapper" as Mapper
participant "factoryUserStory: FactoryUserStoryImpl" as Factory
participant "userStory : UserStory" as UserStory


activate user #FFBBBB
user ->  UI: Selects project and inserts US data\n (projectCode, userStoryId, actor, \ntext, acceptanceCriteria, priority)

activate UI #FFBBBB
UI --> dto ** : create(userStoryId, actor, \ntext, acceptanceCriteria)
UI -> Controller: createUserStory(projectCode, \nuserStoryDTO, priority)

activate Controller #FFBBBB
Controller -> ProjectList: getProject(projectCode)

activate ProjectList #FFBBBB
ProjectList --> Controller: project
deactivate

Controller -> Project : getProductBacklog()

activate Project #FFBBBB
Project --> Controller: productBacklog
deactivate

Controller -> ProductBacklog : createAndAddUserStory(userStoryDTO, priority)

activate ProductBacklog #FFBBBB
ProductBacklog -> Mapper : fromDTO(userStoryDTO, factoryUserStory)

activate Mapper #FFBBBB
Mapper -> Factory : createUserStory(\nuserStoryDTO.userStoryId,\nuserStoryDTO.actor,\nuserStoryDTO.text,\nuserStoryDTO.acceptanceCriteria)

activate Factory #FFBBBB
Factory --> UserStory ** : create(\nuserStoryDTO.userStoryId,\nuserStoryDTO.actor,\nuserStoryDTO.text,\nuserStoryDTO.acceptanceCriteria)
Factory --> Mapper : userStory
deactivate Factory

Mapper --> ProductBacklog: userStory
deactivate Mapper

ProductBacklog -> ProductBacklog : doesNotContain(userStory)
ProductBacklog -> ProductBacklog : add(userStory, priority)

ProductBacklog --> Controller : true
deactivate

Controller --> UI : true
deactivate

UI --> user : Confirms US creation and addition to Product Backlog

@enduml