@startuml
!theme plain
hide footbox
autonumber

skinparam sequence{
LifeLineBackgroundColor #FFBBBB
}

title US017 - As Product Owner, I want to create a user story and add it to the Product Backlog\n(save project in projectRepository)

participant ": ProjectRepository" as projectRepository
participant ": ProjectDataDomainAssembler" as assembler
participant "projectJPA : ProjectJPA" as projectJpa
participant ": ProjectJpaRepository" as jpa

-> projectRepository : save(project)

activate projectRepository
projectRepository -> assembler : toData(project)

activate assembler
assembler --> projectJpa ** : create
assembler --> projectRepository : projectJpa
deactivate

projectRepository -> jpa : save(projectJpa)

activate jpa
jpa --> projectRepository : savedProjectJpa
deactivate

projectRepository -> assembler : toData(savedProjectJpa)

activate assembler
assembler --> savedProject ** : create
assembler --> projectRepository : savedProject
deactivate

[<- projectRepository : savedProject

@enduml