@startuml
!theme plain
hide footbox
autonumber
title "US017 - As Product Owner, I want to create a user story and add it to the Product Backlog"

actor "Product Owner" as user
participant ":CreateUserStoryUI" as UI
participant "userStoryDTO :UserStoryDTO" as dto
participant ":CreateUserStoryController" as Controller
participant ":UserStoryService" as Services
participant ":ProjectRepository" as Repository
participant "factoryUserStory :FactoryUserStoryImpl" as Factory
participant "userStory :UserStory" as UserStory
participant "userStoryRepository :UserStoryRepository" as UsRepository
participant "project : Project" as Project
participant "DATA : HashMap" as hashmap
participant "productBacklog : ProductBacklog" as pb
participant "openUserStories : List<UserStoryID>" as uslist

activate user #FFBBBB
user ->  UI: Selects project and inserts US data\n (projectCode, userStoryNumber, actor, \ntext, acceptanceCriteria, priority)

activate UI #FFBBBB
UI --> dto ** : create(userStoryNumber, actor, \ntext, acceptanceCriteria)
UI -> Controller: createUserStory(projectCode, \nuserStoryDTO, priority)

activate Controller #FFBBBB
Controller -> Services: createUserStory (projectCode,\n userStoryDTO, priority)

activate Services #FFBBBB
Services --> "projectCodeVO : ProjectCode" **: create(projectCode)
Services -> Repository: getByID(projectCodeVO)

activate Repository #FFBBBB
Repository -->Services: project
deactivate

Services --> "userStoryNumber : UserStoryNumber" ** : create(userStoryDTO.userStoryNumber)
Services --> "userStoryID : UserStoryID" ** : create (userStoryNumber, projectCodeVO)
Services --> "actor : UserStoryActor" ** :create (userStoryDTO.actor)
Services --> "acceptanceCriteria : UserStoryAcceptanceCriteria" ** :create (userStoryDTO.acceptanceCriteria)
Services --> "description : Description" ** :create (userStoryDTO.description)
Services -> Factory:createUserStory\n (userStoryID, actor, acceptanceCriteria, description)

activate Factory #FFBBBB
Factory --> UserStory ** :create (userStoryID,\n userStoryActor,\n userStoryAcceptanceCriteria,\n description )
Factory --> Services :userStory
deactivate

Services -> UsRepository :save(userStory)

activate UsRepository #FFBBBB
UsRepository -> hashmap :containsID(userStoryID)
hashmap --> UsRepository : false
UsRepository -> hashmap :put(userStoryID, userStory)
hashmap --> UsRepository : null
UsRepository --> Services: true
deactivate

Services -> Project :addToProductBacklog(userStoryID, priority)

activate Project #FFBBBB
Project -> pb: addUserStory(userStoryID, priority)

activate pb #FFBBBB
pb -> uslist : contains(userStoryID)
uslist --> pb : false
pb -> uslist : add(priority, userStoryID)
pb --> Project : true
deactivate

Project --> Services: true
deactivate
Services --> Controller: true
deactivate
Controller --> UI: true
deactivate
UI --> user: Confirms US creation and addition to Product Backlog.

@enduml