@startuml
!theme plain
hide footbox
title "US016 - As Authenticated User, I want to get a list of all projects I'm currently allocated to"

actor User as User
participant ": UserProjectsUI" as UI
participant ": UserProjectsController" as Controller
participant "userProjectsDTOList: List<UserProjectsDTO>" as DTOList
participant "userProjectsDTO : UserProjectsDTO" as DTO
participant "account : Account" as account
participant ": ProjectList" as ProjectList
participant "project : Project" as Project
participant ": ResourceList" as ResourceList
participant " resource : Resource " as resource

activate User #FFBBBB
User ->  UI: Requests list of projects that User is allocated to

activate UI #FFBBBB
UI -> Controller: listUserProjects(currentAccount)

activate Controller #FFBBBB
Controller -> DTOList ** : create

activate account #FFBBBB
Controller -> account: getEmail()
account --> Controller: email
deactivate account

group loop [for each project]
activate ProjectList #FFBBBB
Controller -> ProjectList : getProjectAtIndex(i)
deactivate ProjectList

loop for each resource

activate Project #FFBBBB
Controller -> Project : getResourceAtIndex(j)
Project -> ResourceList : getResourceAtIndex(j)
activate ResourceList #FFBBBB

ResourceList -> resource : verifyIfUserIsInProject
deactivate ResourceList

activate resource #FFBBBB
resource --> ResourceList  : if emailsMatch && endDateNull &&\n projectCodeNotRepeated  = true
deactivate resource

activate ResourceList #FFBBBB
ResourceList --> Project  : if emailsMatch && endDateNull &&\n projectCodeNotRepeated  = true
deactivate ResourceList


Project -> Project : getProjectCode()
Project -> Project : getProjectName()

Project -> DTO ** : create(projectCode, projectName)
deactivate Project

DTO --> Controller : userProjectsDTO created

Controller -> DTOList : add(userProjectsDTO)
activate DTOList #FFBBBB
deactivate DTOList
end

end

Controller --> UI : userProjectsList
deactivate Controller
deactivate UI

UI --> User: Displays list of project that User is allocated to
deactivate User #FFBBBB
@enduml