@startuml
!theme plain
hide footbox

actor User as User
participant ": UserProjectsUI" as UI
participant ": UserProjectsController" as Controller
participant "userProjectsDTOList: List<UserProjectsDTO>" as DTOList
participant "userProjectsDTO : UserProjectsDTO" as DTO
participant "account : Account" as account
participant "project : Project" as Project
participant ": ProjectList" as ProjectList
participant ": ResourceList" as ResourceList

activate User #FFBBBB
User ->  UI: Requests list of projects that User is allocated to

activate UI #FFBBBB
UI -> Controller: listUserProjects(currentAccount)

activate Controller #FFBBBB
Controller -> DTOList ** : create

activate account #FFBBBB
Controller -> account: getEmail()
account --> Controller: currentAccountEmail
deactivate account

group loop [for each project]
activate ProjectList #FFBBBB
Controller -> ProjectList : project = getProjectAtIndex(i)

loop for each resource
Controller -> Project : resource = getResourceAtIndex(j)
Project -> ResourceList : resource = getResourceAtIndex(j)
activate ResourceList #FFBBBB
deactivate ResourceList


ResourceList -> ResourceList : emailsMatch && endDateNull\n&& projectCodeNotRepeated

end

ResourceList -> ProjectList : emailsMatch && endDateNull &&\n projectCodeNotRepeated  = true
activate ResourceList #FFBBBB
deactivate ResourceList

ProjectList -> Project : projectCode = getProjectCode()
activate Project #FFBBBB
deactivate Project

ProjectList -> Project : projectName = getProjectName()
activate Project #FFBBBB
deactivate Project

ProjectList -> DTO ** : create(projectCode, projectName)

Controller -> DTOList : add(userProjectsDTO)
activate DTOList #FFBBBB
deactivate DTOList
deactivate ProjectList
end

Controller --> UI : userProjectsDTOList
deactivate Controller
deactivate UI

UI --> User: Displays list of project that User is allocated to
deactivate User #FFBBBB
@enduml