@startuml

actor Administrator  as Administrator #white
participant "Change Profile UI" as UI #white
participant "Change Profile Controller" as Controller #white
participant "Profile Account" as Account #white

activate Administrator #FFBBBB
Administrator ->  UI : Associate profile to user (email, profile)
activate UI #FFBBBB
UI -> Controller :  changeProfile(email, profile)
activate Controller #FFBBBB
Controller -> Controller: profileCheck(email, profile)
activate Controller #DarkSalmon


alt#Gold #LightBlue If new profile is user profile
Administrator <-- Controller : Profile already assigned
end
deactivate Controller #DarkSalmon
Controller -> Account : changeProfile (email, profile)
activate Account #FFBBBB
Administrator <-- UI: Successfully associated
@enduml