@startuml

actor Administrator  as Administrator #white
participant "Profile Controller" as Profile #white
participant "Profile Account" as Account #white

Administrator ->  Profile : 1. Associate profile to user (profile)
activate Profile #FFBBBB

Profile -> Profile: 2.Check user profile (profile)
activate Profile #DarkSalmon
deactivate Profile #DarkSalmon

alt#Gold #LightBlue If new profile is user profile
   Administrator <-- Profile : Profile already assigned
end

Profile -> Account : 3.Associate profile to user (profile)
Profile <-- Account: Associated profile

Administrator <-- Profile: Successfully associated
@enduml