@startuml
!theme plain
hide footbox

actor Administrator
participant ": ChangeProfileUI" as UI
participant ": ChangeProfileController" as Controller
participant ": Services" as Services
participant ": AccountList" as AccountList
participant ": ProfileList" as ProfileList
participant "profile : Profile" as Profile
participant "account : ProfileAccount" as Account



activate Administrator #FFBBBB
Administrator -> UI : Associate profile to user (user, profile)
activate UI #FFBBBB
UI -> Controller : changeProfile(email, profileName)
activate Controller #FFBBBB
Controller -> Services : changeProfile(email, profileName)
activate Services #FFBBBB
Services -> AccountList : getAccount(email)
activate AccountList #FFBBBB
deactivate AccountList
Services -> ProfileList : getProfile(profileName)
activate ProfileList #FFBBBB
deactivate ProfileList #FFBBBB
Services -> Account : setProfile(profile)
activate Account #FFBBBB
deactivate Account #FFBBBB

Services --> Controller : Confirms new user profile
Controller --> UI : Confirms new user profile
UI --> Administrator : Confirms new user profile
@enduml