  @startuml

class ChangeProfileUI {}

class ChangeProfileController {
'services : Services
changeProfile(email, newProfileName)
}

class Services {
'accountList : AccountList
'profileList : ProfileList
changeProfile(email, newProfileName)
}

class AccountList {
'accounts : List<Account>
getAccount(email)
}

class ProfileList {
getProfile(profileName)
}

class Account {
name : String
email : String
phone : String
photo : Photo
profile : Profile
isActive : boolean
}

ChangeProfileUI "1" o-- "1" ChangeProfileController
ChangeProfileController "1" o-- "1" Services
Services "1" o-- "1" AccountList
Services "1" o-- "1"  ProfileList
Services ..> Account
AccountList "1" *-- "*" Account : has

@enduml