@startuml
!theme plain
hide footbox

actor Administrator
participant ": ChangeProfileUI" as UI
participant ": ChangeProfileController" as Controller
participant ": AccountList" as AccountList
participant ": ProfileList" as ProfileList
participant "account : ProfileAccount" as Account
participant "profile : Profile" as Profile


activate Administrator
Administrator -> UI : Associate profile to user (user, profile)
activate UI
UI -> Controller : changeProfile(email, profileName)
activate Controller
Controller -> AccountList : account = getAccount(email)
activate AccountList
Controller -> ProfileList : profile = getProfile(profileName)
Controller -> Account : setProfile(profile)
activate Account
deactivate Account
UI --> Administrator : Confirms new user profile
@enduml