@startuml
'https://plantuml.com/sequence-diagram


Administrator -> System: Requests to change profile of user account
Administrator <-- System: Authorization granted
Administrator -> System: Gives new profile to user
Administrator <-- System: Confirms new user profile
@enduml