@startuml

class CreateProfileUI {
}

class CreateProfileController {
createProfile(profileName)
}

class Services {
profileList : ProfileList
createProfile(profileName)
}

class ProfileList {
save(newProfile)
}

class Profile {
name : String
}

CreateProfileUI "        1" o-- "         1" CreateProfileController
CreateProfileController "        1" o-- "         1" Services
Services "                    1" o-- "         1" ProfileList
Services ..> Profile
ProfileList "        1" *-- "                      *" Profile : has

@enduml