@startuml

class CreateProfileUI {
}

class CreateProfileController {
createProfile(profileName)
}

class Services {
profileList : ProfileList
createProfile(profileName)
}

class ProfileList {
profiles : List<Profile>
save(newProfile)
}

class Profile {
name : String
}

CreateProfileUI o-- CreateProfileController
CreateProfileController o-- Services
Services o-- ProfileList
Services ..> Profile
ProfileList "1" *-- "*" Profile : has

@enduml