@startuml
'https://plantuml.com/sequence-diagram

Administrator -> System: Starts Profile creation
Administrator <-- System: Requests Profile designation
Administrator -> System: Gives Profile designation
Administrator <-- System: Confirms Profile creation
@enduml