@startuml
!theme plain
hide footbox
actor Administrator  as Administrator
participant ": CreateProfileUI" as UI
participant ": CreateProfileController" as Controller
participant ": Services" as Services
participant ": ProfileList" as List

activate Administrator #FFBBBB
Administrator ->  UI : Create Profile (profile name)
activate UI #FFBBBB
UI -> Controller : createProfile(profileName)
activate Controller #FFBBBB
Controller -> Services : createProfile(profileName)
activate Services #FFBBBB
Services -> List : createProfile(profileName)
activate List #FFBBBB

List -->"profile : Profile" **
List -> List : add(profile)

Services --> Controller : Confirms Profile creation
Controller --> UI : Confirms Profile creation
UI --> Administrator : Confirms Profile creation
@enduml