@startuml
!theme plain
hide footbox

actor Administrator  as Administrator
participant ": CreateProfileUI" as UI
participant ": CreateProfileController" as Controller
participant ": ProfileList" as List
participant "newProfile : Profile" as profile

activate Administrator #FFBBBB
Administrator ->  UI : Create profile (profile name)

activate UI #FFBBBB
UI -> Controller : createProfile(profileName)

activate Controller #FFBBBB
Controller -> List : createProfile(profileName)

activate List #FFBBBB
List -> List : validateProfileName(profileName)
List --> profile ** : newProfile = create(profileName)
List -> List : add(newProfile)
List --> Controller : Confirms profile creation
deactivate List

Controller --> UI : Confirms profile creation
deactivate Controller
UI --> Administrator : Confirms profile creation
deactivate UI
@enduml