@startuml

class ListProjectUI {}

class ListProjectController{
ListProjectDTO()
}


class Project {
code : Integer
name : String
customer : String
startDate : Date
endDate : Date
projectStatus : String
getCode()
getName()
getCustomer()
getStartDate()
getEndDate()
getStatusProject()
}

class ProjectList {
listSize()
getProjectIndex(i)
create(projectDTO)
}

class ProjectDTO {

}

ProjectList "1" *-- "*" Project : has
ListProjectController "1" o-- "1" ProjectList
ListProjectUI "1" o-- "1" ListProjectController
ProjectList ..> ProjectDTO
ProjectDTO ..> Project

@enduml