@startuml
!theme plain
hide footbox
autonumber
skinparam sequence {
LifeLineBackgroundColor #FFBBBB
}
title "US015 - As Manager, I want to get a list of all projects."

participant Client
participant Springboot
'participant "restDto : ProjectRestDto" as DTOin
participant ": ProjectController" as Controller
participant ": ProjectRestDtoMapper" as Mapper
participant "projectRestDtoList:\n : List<ProjectRestDto>" as projectRestDtoList
participant ": ProjectService" as Service
participant ": IProjectRepository" as ProjRepository
participant ": ProjectDomainDataAssembler" as Assembler
participant ": IProjectJpaRepository" as ProjectJpaRepository
participant "projectJpaList:\n : List<ProjectJpa>" as projectJpaList
participant "projectList:\n : List<Project>" as projectList
participant ": NewProjectDtoMapper" as NewMapper
participant "projectDtoList:\n : List<NewProjectDTO>" as projectDtoList
participant "response:\n : ResponseEntity<ProjectDTO>" as response


Client ->  Springboot: GET /projects {}
activate Springboot
Springboot -> Controller: getAllProjects()
deactivate Springboot
activate Controller

Controller -> Service: getAllProjects()
activate Service

'Saving in the JpaRepository
Service -> ProjRepository : getAllProjects()
activate ProjRepository

ProjRepository -> ProjectJpaRepository : findAll()
activate ProjectJpaRepository

ProjectJpaRepository -> projectJpaList ** : create

ProjectJpaRepository --> ProjRepository : projectsJpaList
deactivate ProjectJpaRepository

ProjRepository -> projectList ** : create
loop for each projectJpa in projectJpaList
ProjRepository -> Assembler : toDomain(projectsJpa)
activate Assembler
Assembler --> ProjRepository: project
deactivate Assembler
ProjRepository -> projectList: add(project)
end

deactivate Assembler

deactivate Assembler

ProjRepository --> Service: projectList
deactivate ProjRepository

Service -> projectDtoList ** : create

loop for each project in projectList
Service -> NewMapper: toDto(project)
activate NewMapper

NewMapper --> Service: projectDto
deactivate NewMapper
Service -> projectDtoList: add(projectDto)

end loop

Service --> Controller : projectDtoList
deactivate Service

Controller -> Mapper: toRestDto(projectDtoList)
activate Mapper

Mapper -> projectRestDtoList ** : create

Mapper --> Controller: projectRestDtoList
deactivate Mapper

Controller --> response ** : create(projectRestDtoListttpStatus.OK)
Controller --> Client : Display all projects
deactivate Controller

@enduml