@startuml
!theme plain
hide footbox
autonumber

skinparam sequence{
LifeLineBackgroundColor #FFBBBB
}

title "US018 - As Product Owner/Scrum Master/Team Member, I want to consult the product backlog, \n i.e. to get the list of user stories sorted by priority."

participant ": UserStoryController" as controller
participant ": UserStoryService" as service
participant ": ProjectRepository" as projectRepo
participant "project : Project" as project
participant ": ProductBacklog" as pb
participant "openUserStoryIDs : List<UserStoryID>" as openUserStoryIDs
participant "openUserStoryList : List<UserStory>" as openUserStoryList
participant ": UserStoryRepository" as usRepo
participant ": NewUserStoryInfoDTOMapper" as domainMapper
participant "productBacklog : List<NewUserStoryInfoDTO>" as dtoList
participant ": UserStoryRestDtoMapper" as restMapper
participant "restDtoList : List<UserStoryRestDto>" as restDtoList
participant "response : ResponseEntity<>" as response

-> controller: GET /projects/{projectCode}/productBacklog

activate controller
controller -> service : getProductBacklog(projectCode)

activate service
service -> projectRepo : getByID(projectCode)

activate projectRepo
projectRepo --> service : project
deactivate projectRepo

service -> project : getProductBacklog()

activate project
project -> pb : getOpenUserStories()

activate pb
pb --> project : openUserStoryIDs
deactivate pb

project --> service : openUserStoryIDs

service --> openUserStoryList ** : create

loop for userStoryID in openUserStoryIDs
service -> usRepo : getByID(userStoryID)

activate usRepo
usRepo --> service : userStory
deactivate usRepo

service -> openUserStoryList : add(userStory)
activate openUserStoryList
deactivate
end

service -> domainMapper : toDtoList(openUserStoryList)

activate domainMapper
domainMapper --> service : dtoList
deactivate domainMapper

service -> service : addPriorities(productBacklog)
activate service
deactivate service

service --> controller : productBacklog
deactivate service

controller -> restMapper : toRestDtoList(productBacklog)

activate restMapper
restMapper --> controller : restDtoList
deactivate restMapper

controller --> response ** : create(restDtoList, HttpStatus.OK)
[<-- controller : response
deactivate controller

@enduml