 @startuml
!theme plain

Object Project {
code
name
description
start date
end date
sprint duration
number of planned sprints
project status
budget
}

Object "ProductBacklog" as PB

Object "UserStory" as US {
id
actor
description
acceptance criteria
status
}

Project "1" -left- "1" PB: includes >
PB "1" -down- "*" US: collects >


@enduml