@startuml
skinparam linetype ortho

class ConsultProductBacklogController {
getProductBacklog(projectCode)
}

class UserStoryServices {
getProductBacklog(projectCode)
}

class ProjectRepository {
containsID(projectCode)
}

class ProjectCode {
id : String
}

class UserStoryRepository {
getProductBacklog(projectCode)
}

class UserStoryMapper{
toDTO(userStoryList)
}

class UserStoryDTO {
id : String
actor : String
text : String
acceptanceCriteria : String
status : Status
}

interface ValueObject {
}

interface DomainID {
}

interface Repository {
}

interface AggregateRoot {
}

interface DomainEntity {
}

ConsultProductBacklogController "1" *-- "1" UserStoryServices
UserStoryServices "1" *-left- "1" ProjectRepository
UserStoryServices "1" *-- "1" UserStoryMapper
UserStoryServices "1" *-- "1" UserStoryRepository
UserStoryMapper ..> UserStoryDTO
UserStoryMapper .left.> UserStoryRepository
UserStoryRepository ..> UserStoryDTO
ProjectCode .up.> ProjectRepository
ProjectCode .up.> UserStoryServices
ProjectCode .right.> UserStoryRepository

UserStoryRepository -..|> Repository
ProjectRepository -..|> Repository
ProjectCode -.down.|> DomainID

DomainID --|> ValueObject

Repository --|> DomainID
Repository --|> AggregateRoot

AggregateRoot --|> DomainID
AggregateRoot --|> DomainEntity

@enduml