@startuml
skinparam linetype ortho

class ConsultProductBacklogController {
getProductBacklog(projectCode)
}

class UserStoryService {
getProductBacklog(projectCode)
getOpenUserStories(List<UserStoryID>)
create(projectCode)
}

class UserStoryRepository {
containsID(id)
containsKey(id)
getByID(id)
}

class ProjectRepository {
getByID(projectCodeVO)
}

class Project{
getProductBacklog()
}

class ProductBacklog {
openUserStories : List<UserStoryID>
getOpenUserStoryIDs()
}

class ProjectCode {
id : String
}

class UserStoryMapper{
toDTO(openUserStoryList)
add(userStoryDTO)
}

class UserStoryDTO {
id : String
actor : String
text : String
acceptanceCriteria : String
status : Status
}

interface ValueObject {
}

interface DomainID {
}

interface Repository {
}

interface AggregateRoot {
}

interface DomainEntity {
}

ConsultProductBacklogController "1" *-- "1" UserStoryService
UserStoryService "1" *-left- "1" ProjectRepository
UserStoryService "1" *-- "1" UserStoryMapper
Project "1" o-- "1" ProductBacklog
UserStoryService "1" *-- "1" Project
UserStoryMapper ..> UserStoryDTO
UserStoryService "1" .right.> "1" UserStoryRepository
UserStoryRepository -..|> Repository
ProjectCode .up.> ProjectRepository
ProjectCode .up.> UserStoryService
ProjectRepository -..|> Repository
ProjectCode -.down.|> DomainID
Project -..|> AggregateRoot
DomainID --|> ValueObject
ProductBacklog ..|> DomainEntity
Repository --|> DomainID
Repository --|> AggregateRoot
AggregateRoot --|> DomainID
AggregateRoot --|> DomainEntity

@enduml