@startuml
!theme plain
hide footbox
title "US018 - As Product Owner/Scrum Master/Team Member, I want to consult the product backlog, \n i.e. to get the list of user stories sorted by priority."

actor "Product Owner/\n/Scrum Master/\n/Team Member" as user
participant ": ConsultProductBacklogUI" as UI
participant ": ConsultProductBacklogController" as Controller
participant ": ProjectList" as ProjectList
participant "project : Project" as Project
participant "productBacklog :\n ProductBacklog" as ProductBacklog
participant ": UserStoryMapper" as Mapper
participant "lsUserStory :\n List<UserStoryDTO>" as DTOList
participant "userStoryList :\n List<UserStory>" as USList


activate user #FFBBBB
user -> UI: Requests product backlog(projectCode)

activate UI #FFBBBB
UI-> Controller:getProductBacklog(projectCode)

activate Controller #FFBBBB
Controller -> ProjectList: getProject(projectCode)
activate ProjectList #FFBBBB
ProjectList--> Controller: project
deactivate ProjectList

Controller -> Project: getProductBacklog()
activate Project #FFBBBB
Project --> Controller: productBacklog
deactivate Project

Controller -> ProductBacklog: getUserStoryList()
activate ProductBacklog #FFBBBB
ProductBacklog --> Controller: userStoryList
deactivate ProductBacklog
Controller -> Mapper : toDTOList(userStoryList)

activate Mapper #FFBBBB
Mapper --> DTOList ** : create

loop for each userStory in userStoryList
Mapper -> Mapper : toDTO(userStory)
Mapper -> DTOList: add(userStoryDTO)
activate DTOList #FFBBBB
deactivate DTOList
end


Mapper --> Controller : lsUserStory
deactivate Mapper


Controller --> UI: lsUserStory
deactivate Controller

UI --> user: Displays product backlog
deactivate UI


@enduml