@startuml
!theme plain
autonumber
hide footbox
title "US018 - As Product Owner/Scrum Master/Team Member, I want to consult the product backlog, \n i.e. to get the list of user stories sorted by priority."

actor "Product Owner/\n/Scrum Master/\n/Team Member" as user
participant ": ConsultProductBacklogUI" as UI
participant ": ConsultProductBacklogController" as Controller
participant ": UserStoryServices" as Services
participant ": ProjectRepository" as ProjRepository
participant ": UserStoryMapper" as Mapper
participant ": UserStoryRepository" as Repository
participant "lsUserStory :\n List<UserStoryDTO>" as DTOList

activate user #FFBBBB
user -> UI: Requests product backlog(projectCode)

activate UI #FFBBBB
UI-> Controller:getProductBacklog(projectCode)

activate Controller #FFBBBB

Controller -> Services: getProductBacklog(projectCode)
activate Services #FFBBBB

Services -> ProjRepository: containsID(projectCode)
activate ProjRepository #FFBBBB
ProjRepository --> Services: true
deactivate ProjRepository
Services -> Repository: getProductBacklog(projectCode)
activate Repository #FFBBBB
Repository --> Services: productBacklog
deactivate
Services -> Mapper: toDTO(userStoryList)
activate Mapper #FFBBBB

Mapper --> DTOList ** : create

loop for each userStory in UserStoryRepository
Repository --> Mapper : userStory
deactivate Repository
Mapper -> Mapper : toDTO(userStory)
Mapper -> DTOList: add(userStoryDTO)
activate DTOList #FFBBBB
deactivate DTOList
end

Mapper --> Services : productBacklog
deactivate Mapper

Services --> Controller : productBacklog
deactivate Services

Controller --> UI: productBacklog
deactivate Controller

UI --> user: Displays product backlog
deactivate UI

@enduml