@startuml

class ListResourcesUI {
}

class ListResourcesController{
projectList : ProjectList
lsResouces : ResourcesDTO
listResources(projectCode)
}

class ProjectList{
projectList : ProjectList
project : Project
lsResources : ResourcesDTO
getProject(projectCode)
listResources(project)
}
'In class Project, all attributes not relevant for US014
'are omitted
class Project {
projectCode : String
resourceList : ResourceList
lsResources : ResourcesDTO
listResources()
}

class ResourceList{
resourceList : ResourceList
resource : Resource
lsResources : ResourcesDTO
createResourcesDTO()
getEmailOfResource()
}

class Resource {
account : Account
role : Role
startDate : Date
endDate : Date
percentAllocation : float
costPerHour : float
getEmailOfResource()
getRole()
createResourceDTO()
addResourceDTO(lsResources)
}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
getEmail()
}

ListResourcesUI "1 " o-- "1 " ListResourcesController
ListResourcesController "1 " o-- "1 " ProjectList
ProjectList "1 " *-- " * " Project : has
Project "1 " o-- "1 " ResourceList
ResourceList "1 " *-- " * " Resource : has
Resource "1 " o-- "1 " Account : has

@enduml