@startuml
!theme plain
hide footbox

actor Manager as Manager
participant ": ListResourcesUI" as UI
participant ": ListResourcesController" as Controller
participant ": ProjectList" as ProjectList
participant "project : Project" as project
participant ": ResourceList" as ResourceList
participant "lsResources :\n List<ResourceDTO>" as DTOList
participant "resource : Resource" as Resource
participant "resourceDTO : ResourceDTO" as DTO
participant " account : Account" as account

activate Manager #FFBBBB
Manager ->  UI: Requests list of all human resources in a project (projectCode)

activate UI #FFBBBB
UI -> Controller: listResources(projectCode)

activate Controller #FFBBBB
Controller -> ProjectList: getProject()
activate ProjectList #FFBBBB
ProjectList --> Controller : project
deactivate ProjectList

Controller -> project : listResources(project)
activate project #FFBBBB
project -> ResourceList : listResources()
activate ResourceList #FFBBBB
ResourceList -> DTOList ** : create

loop for each resource
ResourceList -> Resource : createResourceDTO(resource)
activate Resource #FFBBBB
Resource -> account : getEmail()
activate account #FFBBBB
account --> Resource : email

deactivate account
Resource -> Resource : getRole()
Resource -> DTO ** : create(email, role)
Resource -> ResourceList : resourceDTO
deactivate Resource

ResourceList -> DTOList : add(resourceDTO)
activate DTOList #FFBBBB

end

deactivate DTOList
ResourceList --> project : lsResources
deactivate ResourceList
project --> Controller : lsResources
deactivate project

Controller --> UI : lsResources
deactivate Controller

UI --> Manager: Displays list of human resources in a project (projectCode)
deactivate UI
deactivate Manager #FFBBBB
@enduml