@startuml
left to right direction

:Profile: as Profile
Profile <|-- :Manager:

rectangle "Project Management System"{

:Manager: as Manager
Manager -- (List of all human resources in a project )

}
@enduml