@startuml
!theme plain
autonumber
hide footbox
title "US007 - As Administrator, I want to create a new project typology"

actor Administrator
participant ": CreateTypologyUI" as UI
participant ": CreateTypologyController" as Controller
participant ": TypologyService" as Service
participant "typologyFactory : ITypologyFactory" as Factory
participant "typologyRepository : TypologyRepository" as Repository
participant ": AssemblerData" as Assembler
participant "typologyRepositoryJPA: ITypologyRepositoryJPA" as RepositoryJPA

activate Administrator #FFBBBB
Administrator -> UI : Create typology (designation)

activate UI #FFBBBB
UI -> Controller : createTypology(designation)

activate Controller #FFBBBB
Controller -> Service : createTypology(designation)

activate Service #FFBBBB
Service --> "typologyDesignation : TypologyDesignation" ** : create(designation)

Service -> Factory : createTypology(typologyDesignation)
activate Factory #FFBBBB
Factory --> "typology : Typology" ** : create(typologyDesignation)
Factory --> Service : typology
deactivate Factory

Service -> Repository : save(typology)
activate Repository #FFBBBB


Repository -> Assembler : toData(typology)
activate Assembler #FFBBBB
Assembler --> Repository: typologyJPA
deactivate Assembler

Repository -> RepositoryJPA : save(typologyJPA)
activate RepositoryJPA #FFBBBB
RepositoryJPA --> Repository : savedTypologyJPA
deactivate RepositoryJPA
Repository -> Assembler : toDomain(savedTypologyJPA)
activate Assembler #FFBBBB
Assembler --> Repository : savedTypology
deactivate Assembler
Repository -->Service: savedTypology


deactivate Repository
Service --> Controller : true
deactivate Service
Controller --> UI : Confirms typology creation
deactivate Controller

UI --> Administrator : Confirms typology creation
deactivate UI

@enduml