@startuml
!theme plain
hide footbox
title "US007 - As Administrator, I want to create a new project typology"

actor Administrator
participant ": CreateTypologyUI" as UI
participant ": CreateTypologyController" as Controller
participant ": TypologyList" as List
participant "newTypology : Typology" as typology

activate Administrator #FFBBBB
Administrator -> UI : Create typology (typology designation)

activate UI #FFBBBB
UI -> Controller : createTypology(typologyDesignation)

activate Controller #FFBBBB
Controller -> List : createTypology(typologyDesignation)

activate List #FFBBBB
List --> typology  ** : create(typologyDesignation)
List -> List : listDoesNotContain(newTypology)
List -> List : add(newTypology)
List --> Controller : Confirms typology creation
deactivate List

Controller --> UI : Confirms typology creation
deactivate Controller

UI --> Administrator : Confirms typology creation
deactivate UI

@enduml