@startuml
!theme plain
autonumber
skinparam sequence {
LifeLineBackgroundColor #FFBBBB
}
hide footbox
title "US007 - As Administrator, I want to create a new project typology"

participant Client
participant Springboot
participant "typologyDTO : TypologyDTO" as typologyDTO
participant ": TypologyController" as Controller
participant ": TypologyService" as Service
participant ": ITypologyFactory" as Factory
participant ": ITypologyRepository" as Repository
participant ": TypologyDomainDataAssembler" as Assembler
participant ": ITypologyJpaRepository" as RepositoryJPA
participant "typology : Typology" as typology
participant "typologyJPA : TypologyJPA" as typologyJPA
participant "savedTypology : Typology" as savedTypology
participant ":TypologyMapper" as Mapper
participant "response : ResponseEntity<TypologyDTO>" as response

Client -> Springboot : POST /typologies \n{"typology": "typologyDesignation"}
activate Client

activate Springboot
Springboot --> typologyDTO ** : create(typologyDesignation)
Springboot -> Controller : createTypology\n(typologyDTO)
deactivate Springboot

activate Controller
Controller -> Service : createTypology\n(typologyDTO)

activate Service

Service -> Factory : createTypology\n(typologyDesignation)
activate Factory

Factory --> typology ** : create\n(typologyDesignation)
Factory --> Service : typology
deactivate Factory

Service -> Repository : save(typology)
activate Repository

Repository -> Repository: containsTypologyDesignation\n(typologyDesignation)
activate Repository #DarkSalmon

Repository -> RepositoryJPA: existsByTypologyDesignation\n(typologyDesignation)
activate RepositoryJPA
RepositoryJPA --> Repository: false
deactivate Repository
deactivate RepositoryJPA

Repository -> Assembler : toData(typology)
activate Assembler
Assembler -> typologyJPA ** : create
Assembler --> Repository: typologyJPA
deactivate Assembler

Repository -> RepositoryJPA : save(typologyJPA)
activate RepositoryJPA
RepositoryJPA --> Repository : savedTypologyJPA
deactivate RepositoryJPA
Repository -> Assembler : toDomain(savedTypologyJPA)
activate Assembler
Assembler -> savedTypology ** : create
Assembler --> Repository : savedTypology
deactivate Assembler

Repository -->Service: savedTypology
deactivate Repository

Service --> Controller : typologyDTO
deactivate Service

Controller -> Mapper :toOutputDTO(typologyDTO)
activate Mapper #FFBBBB
Mapper -->"typologyOutputDTO:TypologyOutputDTO" ** :Create(typologyDTO)
Mapper --> Controller :typologyOutputDTO
deactivate Mapper

Controller --> response ** : create(savedTypology, HttpStatus.CREATED)
Controller --> Client : Confirms typology creation
deactivate Controller

@enduml