@startuml
!theme plain
hide footbox
actor Administrator  as Administrator
participant ": RegisterAccountUI" as UI
participant ": RegisterAccountController" as Controller
participant ": Services" as Services
participant ": ProfileList" as ProfileList
participant " defaultProfile : Profile"
participant " newAccount : Account" as newAccount
participant ": AccountList" as List

activate Administrator #FFBBBB
Administrator ->  UI : Register user (name, email, phone, photo)
activate UI #FFBBBB
UI -> Controller : registerAccount(name, email, phone, photo)
activate Controller #FFBBBB
Controller -> Services : registerAccount(name, email, phone, photo)
activate Services #FFBBBB
Services -> ProfileList : defaultProfile = getProfile("User")
activate ProfileList #FFBBBB
deactivate ProfileList
Services --> newAccount ** : newAccount = create(name, email, phone, photo, defaultProfile)
Services -> List : save(newAccount)

activate List #FFBBBB
deactivate List

'List -> List : emailExists(email)

'List -> List : add(newAccount)
'List --> Services : Confirms new account registration
Services --> Controller : Confirms new account registration
deactivate Services
Controller --> UI : Confirms new account registration
deactivate Controller
UI --> Administrator : Confirms new account registration
deactivate UI
@enduml