@startuml
!theme plain
hide footbox
actor Administrator  as Administrator
participant ": RegisterAccountUI" as UI
participant ": RegisterAccountController" as Controller
participant ": Services" as Services
participant ": AccountList" as List

activate Administrator #FFBBBB
Administrator ->  UI : Register user (name, email, phone, photo)
activate UI #FFBBBB
UI -> Controller : registerAccount(name, email, phone, photo)
activate Controller #FFBBBB
Controller -> Services : registerAccount(name, email, phone, photo)
activate Services #FFBBBB
Services -> List : registerAccount(name, email, phone, photo)
activate List #FFBBBB

'List -> List : emailExists(email)
List -->" newAccount : ProfileAccount" ** : create(name, email, phone, photo)
List -> List : add(newAccount)
List --> Services : Confirms new account registered
Services --> Controller : Confirms new account registered
Controller --> UI : Confirms new account registered
UI --> Administrator : Confirms new account registered
@enduml