@startuml

class RegisterAccountUI {}

class RegisterAccountController {
services : Services
registerAccount(name, email, phone)
registerAccount(name, email, phone, photo)
}

class Services {
accountList : AccountList
profileList : ProfileList
registerAccount(name, email, phone)
registerAccount(name, email, phone, photo)
}

class ProfileList {
profiles: List<Profile>
}

class AccountList {
accounts : List<Account>
save(newAccount)
}

class Profile {
name: String
}

class Account {
name : String
email : String
phone : String
photo : Photo
profile : Profile
isActive : boolean
}

RegisterAccountUI o-- RegisterAccountController
RegisterAccountController o-- Services
Services o-- ProfileList
Services ..> Profile
Services o-- AccountList
Services ..> Account
Account ..> Profile
AccountList "1" *-- "*" Account : has
ProfileList "1" *-- "*" Profile : has

@enduml