@startuml
!theme plain


title "Architectural Design Model - Logical View Level 2"

"<<component>>\n<<C4 Context>>\nproject-g3" as system
() "UI" as ui
() "REST API" as api

component system {

    component "<<component>>\n<<C4 Container>>\nFrontend" {
        portout " " as p1
        port " " as p2
    }

    component "<<component>>\n<<C4 Container>>\nBackend" {
        port " " as p3
        portout " " as dbport
    }

    ' client uses server API
    p1 -- p3

    portout " " as p4
    portout " " as p5

    ' client presents UI
    p2 -- p4
    p4 -- ui

    ' server presents API
    p3 -- p5
    p5 -- api

    component "<<component>>\n<<C4 Container>>\nDatabase" {
        port " " as p6
    }

    () "SQL API" as dbAPI

    dbAPI -- p6
    dbport --( dbAPI

}

@enduml