@startuml
!theme plain

title "Architectural Design Model - Logical View Level 1"

[<<component>>\n<<C4 Context>>\nProject-g3] as system
() "REST API" as api
() "UI" as ui

system #-u- api
system #-u- ui

@enduml