@startuml

title Architectural Design Model - Physical View Level 2

folder "Project-g3" {

    node "localhost :" as localhost {

        component "<<component>>\nBrowser" {

            ["<<component>>\n<<Container C4>>\nFrontend"]

        }

    }

    node " : " as server {

        ["<<component>>\n<<Container C4>>\nBackend"]

    }

    localhost <--> server : HTTP/S

    node " : " as dbserver {

        ["<<component>>\n<<Container C4>>\nDatabase"]
    }

    server <--> dbserver : TCP/IP

}

@enduml