@startuml
!theme plain
skinparam sequence {
LifeLineBackgroundColor #FFBBBB
}
title "US023 - As a Manager, I want to create a Project in the web UI."

participant Manager
participant Client
participant Server
participant Database

Manager -> Client: I want to create a project
activate Client
Client -> Client: Show UI
Client --> Manager: Ask for data
Manager -> Client: Create project (code, name, description, \n start date, end date, budget, sprint duration,\n number of planned sprints)
Client -> Server: Post{project body}
activate Server
Server -> Database: save project
activate Database
Database --> Server: confirm saved project
deactivate Database
Server --> Client: 201
deactivate Server
Client -> Client: Generate UI
Manager <-- Client: Confirms project creation.
@enduml