@startuml

class AccountStatusUI {
}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
inactivateAccount()
}

class AccountStatusController {
changeAccountStatus(email, inactive)
}

class Services {
accountList : AccountList
changeAccountStatus(email, inactive)
}

class "AccountList" {
getAccount(email)
}

AccountStatusUI o-- AccountStatusController
AccountStatusController o-- Services
Services ..> Account
Services ..> "AccountList"
AccountList "1" *-- "*" Account : has

@enduml