@startuml
!theme plain
hide footbox

actor Administrator  as Administrator #white
participant ": AccountStatusUI" as UI #white
participant ": AccountStatusController" as Controller #white
participant ": Services" as Services #white
participant ": AccountList" as AccountList #white
participant "account : Account" as Account #white

'Administrator ->  Controller : 1.Choose account and request inactivation
Administrator ->  UI : Choose account and request inactivation (email)
activate UI #FFBBBB
'activate Controller #FFBBBB
activate Administrator #FFBBBB
UI -> Controller: changeAccountStatus(email, inactive)
activate Controller #FFBBBB
Controller -> Services: changeAccountStatus(email, inactive)
activate Services #FFBBBB
Services -> AccountList: account = getAccount(email)
activate AccountList #FFBBBB
deactivate AccountList
Services -> Account: inactivateAccount()
activate Account #FFBBBB
deactivate Account
Services --> Controller : Successfully inactivated
deactivate Services
Controller --> UI : Successfully inactivated
deactivate Controller
UI --> Administrator: Successfully inactivated
@enduml