@startuml

class AccountStatusUI {
}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
inactivateAccount()
}

class AccountStatusController {
changeAccountStatus(email, inactive)
}

class Services {
changeAccountStatus(email, inactive)
}

class "AccountList" {
getAccount(email)
}

AccountStatusUI "1" o-- "1" AccountStatusController
AccountStatusController "1" o-- "1" Services
Services ..> Account
Services "1" o-- "1  " "AccountList"
AccountList "1  " *-- "*" Account : has

@enduml