@startuml

class Profile {
name : String
}

class ProfileList {
profiles : List<Profile>
save(profile)
getProfile(profileName)
}

class ListAccountsController{
listAccounts()
}

class CreateProfileController {
createProfile(profileName)
}

class RegisterAccountController {
createProfile(profileName)
registerAccount(name, email, phone, photo)
}

class ChangeProfileController {
changeProfile(email, newProfileName)
}

class AccountStatusController {
changeAccountStatus(email, inactive)
}

class Services {
accountList : AccountList
profileList: ProfileList
listAccounts()
createProfile(profileName)
registerAccount(name, email, phone, photo)
changeProfile(email, newProfileName)
changeAccountStatus(email, inactive)

}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
inactivateAccount()
}

class AccountList {
accounts: List<Account>
getAccountAtIndex(index)
registerAccount(name, email, phone, photo)
save(newAccount)
getAccount(email)
}

class AccountDTO {
email : String
isActive : boolean
create(email, status)
}

Services ..> Account
Services ..> AccountList
Services --> AccountDTO

AccountList --> Account

UI ..> ListAccountsController
UI ..> CreateProfileController
UI ..> RegisterAccountController
UI ..> ChangeProfileController
UI ..> AccountStatusController

ListAccountsController ..> Services
CreateProfileController ..> Services
RegisterAccountController ..> Services
ChangeProfileController..> Services
AccountStatusController ..> Services
@enduml