@startuml

' UIs
class CreateProfileUI {}
class RegisterAccountUI {}
class ChangeProfileUI {}
class ListAccountsUI {}
class AccountStatusUI {}

' Controllers
class CreateProfileController {
createProfile(profileName)
}

class RegisterAccountController {
registerAccount(name, email, phone)
registerAccount(name, email, phone, photo)
}

class ChangeProfileController {
changeProfile(email, newProfileName)
}

class ListAccountsController{
listAccounts()
}

class AccountStatusController {
changeAccountStatus(email, newStatus)
}

' Business Layer
class Services {
accountList : AccountList
profileList: ProfileList
listAccounts()
createProfile(profileName)
registerAccount(name, email, phone)
registerAccount(name, email, phone, photo)
changeProfile(email, newProfileName)
changeAccountStatus(email, newStatus)
}

class Profile {
name : String
}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
inactivateAccount()
}

class AccountDTO {
email : String
isActive : boolean
create(email, status)
}

' Data Access Layer

class ProfileList {
profiles : List<Profile>
getProfile(profileName)
save(profile)
}

class AccountList {
accounts: List<Account>
getAccountAtIndex(index)
registerAccount(name, email, phone, photo)
save(newAccount)
getAccount(email)
}

' Associations and dependencies

CreateProfileUI ..> CreateProfileController
CreateProfileController ..> Services
Services ..> ProfileList
Services ..> Profile
ProfileList "1" --> "*" Profile : has

RegisterAccountUI ..> RegisterAccountController
RegisterAccountController ..> Services
Services ..> AccountList
Services ..> Account
Account ..> Profile
AccountList "1" --> "*" Account : has

ChangeProfileUI ..> ChangeProfileController
ChangeProfileController ..> Services

ListAccountsController ..> Services
ListAccountsUI ..> ListAccountsController
Services ..> AccountDTO
AccountDTO ..> Account

AccountStatusController ..> Services
AccountStatusUI ..> AccountStatusController

@enduml