@startuml

[CreateSprintContainer] as Sprint
[Button] as Button
[AutoNumber] as Number
[SaveButton] as Save
[CancelButton] as Cancel
[DateInput] as Date
[StartDateInput] as SDate
[EndDateInput] as EDate


Sprint -- Button
Sprint -- Date
Sprint -- Number
Button -- Save
Button -- Cancel
Date -- SDate
Date -- EDate

@enduml