@startuml
!theme plain
hide footbox
autonumber
title "US012 -As Manager, I want to define the PO of a project"

participant Client
participant Springboot
participant "resourceDTO:ResourceDTO" as dto
participant ": ResourceController" as Controller
participant ": ResourceService" as Services
participant ": AccountRepository" as AccountRepository
participant ": AccountRepositoryJPA" as AccountRepositoryJPA
participant "account : Account" as account
participant ": ProjectRepository" as ProjectRepository
participant ": ProjectRepositoryJPA" as ProjectRepositoryJPA
participant ": ResourceRepository" as ResourceRepository
participant ": ResourceRepositoryJPA" as ResourceRepositoryJPA
participant "resource : Resource" as resource
participant ": AssemblerData" as AssemblerData

activate Client #FFBBBB
Client -> Springboot : POST /projects/${projectCode}/resource {"projectCode":"projectCode",\n (email, role, projectCode, startDate, endDate,\n percentAllocation, costPerHour)

activate Springboot #FFBBBB
Springboot --> dto ** : create(email, role, projectCode,startDate,\n endDate, percentAllocation, costPerHour)
Springboot -> Controller : createResource(resourceDTO)
activate Controller #FFBBBB
Controller -> Services : createResource(resourceDTO)
activate Services #FFBBBB



Services -> AccountRepository : getByEmail(email)
activate AccountRepository #FFBBBB

AccountRepository --> Services : Account
deactivate AccountRepository


Services -> account : isUser()
activate account #FFBBBB
account --> Services : true
deactivate account

Services -> ProjectRepository : existsByProjectCode(projectCode)
activate ProjectRepository #FFBBBB
ProjectRepository --> Services : true
deactivate ProjectRepository

Services -> Factory: createResource(resourceID, email, role, projectCode, timePeriod, percentAllocation, costPerHour)
activate Factory #FFBBBB
Factory --> resource ** : createResource(resourceID, email, roleName,\n projectCode, timePeriod, percentAllocation, costPerHour)
Factory --> Services: resource
deactivate Factory

Services -> ResourceRepository : save(resource)
activate ResourceRepository #FFBBBB
ResourceRepository -> ResourceRepositoryJPA : toData(resource)
activate ResourceRepositoryJPA #FFBBBB
ResourceRepositoryJPA --> "resourceJPA : ResourceJPA" **: create
ResourceRepositoryJPA --> ResourceRepository : resourceJPA
deactivate ResourceRepositoryJPA
ResourceRepository -> AssemblerData : save(resourceJPA)
activate AssemblerData #FFBBBB
AssemblerData --> ResourceRepository : savedResourceJPA
deactivate AssemblerData
ResourceRepository -> ResourceRepositoryJPA: toDomain(savedResourceJPA)
activate ResourceRepositoryJPA #FFBBBB
ResourceRepositoryJPA --> "savedResource" **: create
ResourceRepositoryJPA --> ResourceRepository : savedResource
deactivate ResourceRepositoryJPA
ResourceRepository -> Services : true
deactivate ResourceRepository
Services --> Controller : true
deactivate Services
Controller --> Springboot: true
deactivate Controller

Springboot --> Client : confirm
deactivate Springboot

deactivate Client

@enduml