@startuml

[UserStoryContainer] as CRContainer
[CreateUSForm] as USForm
[FormText] as Form
[FormButton] as Button
[SaveButton] as Save
[CancelButton] as Cancel
[InputForm] as IForm
[TextAreaForm] as TArea

CRContainer -- USForm
USForm -- Form
USForm -- Button
Button -- Save
Button -- Cancel
Form -- IForm
Form -- TArea

@enduml