@startuml
'https://plantuml.com/salt

salt

<style>
title {
  HorizontalAlignment center
  FontSize 18
  FontColor black
}
</style>

title <b>Create User Story</b>
{+

<b> Number
{+ "          "}
<b> Actor
{+ "                                     "}
<b> Description
{+ "                                     "}
<b> Priority</b> (optional)
{+ "          "}
{<b>Acceptance criteria
{+
   Enter acceptance criteria here

   .
   "                         "
}


}
{ [<&circle-check>Save ] |  [<&circle-x>Cancel] }
}
@enduml