@startuml
'https://plantuml.com/sequence-diagram

Administrator -> System: Selects inactive User Account
Administrator -> System: Requests User Account activation
Administrator <-- System: Confirms User Account activation

@enduml