@startuml
left to right direction

Profile <|-- :Administrator:

rectangle "Project Management System"{
:Administrator: as Administrator
Administrator -- (Edit other user account information \n including activating)
}

@enduml