@startuml
!theme plain
hide footbox
actor Administrator  as Administrator #white
participant ": AccountStatusUI" as UI #white
participant ": AccountStatusController" as Controller #white
participant ": AccountList" as AccountList #white
participant "account : Account" as Account #white

Administrator ->  UI : Choose account and request activation (email)
activate UI #FFBBBB
activate Administrator #FFBBBB
UI -> Controller: changeAccountStatus(email, active)
activate Controller #FFBBBB
activate Controller #FFBBBB
Controller -> AccountList: account = getAccount(email)
activate AccountList #FFBBBB
deactivate AccountList
Controller -> Account: activateAccount()
activate Account #FFBBBB
Account --> Controller : Successfully activated
deactivate Account
Controller --> UI : Successfully activated
deactivate Controller
UI --> Administrator: Successfully activated
@endumml