@startuml

class AccountStatusUI {
}

class Account {
profile : Profile
name : String
email : String
phone : String
photo : Photo
isActive : boolean
activateAccount()
}

class AccountStatusController {
changeAccountStatus(email, active)
}

class Services {
changeAccountStatus(email, active)
}

class "AccountList" {
getAccount(email)
}

Services ..> Account
Services "1" o-- "1  " "AccountList"
AccountList "1  " *-- "*" Account : has
AccountStatusController "1" o-- "1" Services
AccountStatusUI "1" o-- "1" AccountStatusController

@enduml